# Generated by Django 3.1.7 on 2021-06-04 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20210604_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='ship_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.address'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookItems', to='business.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='business.order'),
        ),
    ]
