# Generated by Django 3.1.7 on 2021-06-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20210604_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
