# Generated by Django 3.1.7 on 2021-06-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20210604_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='city_or_province',
        ),
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
    ]
