# Generated by Django 3.1.7 on 2021-06-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20210604_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='expected_ship_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
